services:
  backend:
    image: ghcr.io/xbarrufet/40kdb-backend:latest
    restart: unless-stopped
    volumes:
      - /home/xavier/40kdb/data:/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    expose:
      - "5050"

  frontend:
    image: ghcr.io/xbarrufet/40kdb-frontend:latest
    restart: unless-stopped
    ports:
      - "4000:80"
    depends_on:
      - backend
