// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _40kdb.Data;

#nullable disable

namespace _40kdb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260624052403_AddProjects")]
    partial class AddProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.17");

            modelBuilder.Entity("_40kdb.Models.Faction", b =>
                {
                    b.Property<int>("FactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FactionGroup")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FactionId");

                    b.HasIndex("GameId", "Name")
                        .IsUnique();

                    b.ToTable("Factions");
                });

            modelBuilder.Entity("_40kdb.Models.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("_40kdb.Models.Miniature", b =>
                {
                    b.Property<int>("MiniatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BaseMagnetized")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BasePainted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DecalsApplied")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Edition")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Original")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Proxy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UnitId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MiniatureId");

                    b.HasIndex("UnitId");

                    b.ToTable("Miniatures");
                });

            modelBuilder.Entity("_40kdb.Models.Phase", b =>
                {
                    b.Property<int>("PhaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("PhaseId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Phases");
                });

            modelBuilder.Entity("_40kdb.Models.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectId");

                    b.HasIndex("GameId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("_40kdb.Models.ProjectMiniature", b =>
                {
                    b.Property<int>("ProjectId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MiniatureId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhaseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProjectId", "MiniatureId");

                    b.HasIndex("MiniatureId");

                    b.HasIndex("PhaseId", "MiniatureId")
                        .IsUnique();

                    b.ToTable("ProjectMiniatures");
                });

            modelBuilder.Entity("_40kdb.Models.Unit", b =>
                {
                    b.Property<int>("UnitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FactionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("UnitId");

                    b.HasIndex("FactionId", "Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("_40kdb.Models.Faction", b =>
                {
                    b.HasOne("_40kdb.Models.Game", "Game")
                        .WithMany("Factions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("_40kdb.Models.Miniature", b =>
                {
                    b.HasOne("_40kdb.Models.Unit", "Unit")
                        .WithMany("Miniatures")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("_40kdb.Models.Phase", b =>
                {
                    b.HasOne("_40kdb.Models.Project", "Project")
                        .WithMany("Phases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("_40kdb.Models.Project", b =>
                {
                    b.HasOne("_40kdb.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("_40kdb.Models.ProjectMiniature", b =>
                {
                    b.HasOne("_40kdb.Models.Miniature", "Miniature")
                        .WithMany()
                        .HasForeignKey("MiniatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_40kdb.Models.Phase", "Phase")
                        .WithMany()
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("_40kdb.Models.Project", "Project")
                        .WithMany("ProjectMiniatures")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Miniature");

                    b.Navigation("Phase");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("_40kdb.Models.Unit", b =>
                {
                    b.HasOne("_40kdb.Models.Faction", "Faction")
                        .WithMany("Units")
                        .HasForeignKey("FactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Faction");
                });

            modelBuilder.Entity("_40kdb.Models.Faction", b =>
                {
                    b.Navigation("Units");
                });

            modelBuilder.Entity("_40kdb.Models.Game", b =>
                {
                    b.Navigation("Factions");
                });

            modelBuilder.Entity("_40kdb.Models.Project", b =>
                {
                    b.Navigation("Phases");

                    b.Navigation("ProjectMiniatures");
                });

            modelBuilder.Entity("_40kdb.Models.Unit", b =>
                {
                    b.Navigation("Miniatures");
                });
#pragma warning restore 612, 618
        }
    }
}
